CREATE TABLE IF NOT EXISTS persons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  tel TEXT,
  email TEXT UNIQUE NOT NULL,
  address TEXT,
  photo TEXT
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  start DATETIME NOT NULL,
  end DATETIME NOT NULL,
  CHECK (start < end)
);

CREATE TABLE IF NOT EXISTS event_attendees (
  event_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  PRIMARY KEY (event_id, person_id),
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  published DATETIME NOT NULL,
  summary TEXT NOT NULL,
  content TEXT NOT NULL, -- Storing HTML content
  FOREIGN KEY (author_id) REFERENCES persons(id) ON DELETE CASCADE
);